### ISSUE TITLE
Unclear error message when passing null values to updateMany

### ISSUE THREAD

**Issue by LeonardMeyer** [typelevel/doobie#809]
I was trying to do an `updateMany()` and have a nullable FK in my table. So I just put `null` inside my tuple... And here we are I guess ?
```
java.lang.RuntimeException: oops, null
	at scala.sys.package$.error(package.scala:27)
	at doobie.util.Put.unsafeSetNonNullable(put.scala:36)
	at doobie.util.Write$$anonfun$fromPut$2.apply(write.scala:64)
	at doobie.util.Write$$anonfun$fromPut$2.apply(write.scala:64)
	at doobie.util.LowerPriorityWrite$$anonfun$product$5.apply(write.scala:99)
	at doobie.util.LowerPriorityWrite$$anonfun$product$5.apply(write.scala:99)
	at doobie.util.LowerPriorityWrite$$anonfun$product$5.apply(write.scala:99)
	at doobie.util.LowerPriorityWrite$$anonfun$product$5.apply(write.scala:99)
	at doobie.util.LowerPriorityWrite$$anonfun$product$5.apply(write.scala:99)
	at doobie.util.LowerPriorityWrite$$anonfun$product$5.apply(write.scala:99)
	at doobie.util.LowerPriorityWrite$$anonfun$product$5.apply(write.scala:99)
	at doobie.util.LowerPriorityWrite$$anonfun$product$5.apply(write.scala:99)
	at doobie.util.LowerPriorityWrite$$anonfun$product$5.apply(write.scala:99)
	at doobie.util.LowerPriorityWrite$$anonfun$product$5.apply(write.scala:99)
	at doobie.util.LowerPriorityWrite$$anonfun$generic$2.apply(write.scala:110)
	at doobie.util.LowerPriorityWrite$$anonfun$generic$2.apply(write.scala:110)
	at doobie.util.Write$$anonfun$set$1.apply(write.scala:24)
	at doobie.util.Write$$anonfun$set$1.apply(write.scala:24)
	at doobie.free.KleisliInterpreter$$anonfun$primitive$1$$anonfun$apply$1.apply(kleisliinterpreter.scala:114)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
	at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:86)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.cats$effect$internals$TrampolineEC$JVMTrampoline$$super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline$$anonfun$startLoop$1.apply$mcV$sp(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline$$anonfun$startLoop$1.apply(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline$$anonfun$startLoop$1.apply(TrampolineEC.scala:93)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:92)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:72)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:52)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:351)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:372)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```scala
type Tupled = (String, String, String, String, String)
val tuples = ??? // construction with null as last column
Update[Tupled]("INSERT INTO table (stuff1, stuff2, stuff3, stuff4, stuff5) VALUES (?, ?, ?, ?, ?)")
.updateMany(tuples)
```

Of course I realized I should use `Option` so nothing too bad, but I think the error message could be hinting at it or something.

**Comment by anton-zen** [comment]
It's also a RuntimeException. I wonder if it could be more specific Exception class.

**Comment by jatcwang** [comment]
Yes I think the error message can be improved

**Comment by felix-hedenstrom** [comment]
Is this issue fixed as of https://github.com/typelevel/doobie/pull/2142?

**Comment by jatcwang** [comment]
Yes it is!
